### ISSUE TITLE
Unable to create the graph

### ISSUE THREAD

**Issue by michaelklem** [banjtheman/polygon_nft_workshop#1]
The process to create the graph in step 13 must have changed. Also it seems that the graphs that can be created do not support polygon. So when I try to run the graph cli, it can never find my contract.

The command I am told to use by graph is:
graph init --product hosted-service michaelklem/test

The error is:
Ethereum network · mumbai
✔ Contract address · 0x3d3C0F4F5903C68f4635066c0DCc902F0CD54D4a
✖ Failed to fetch ABI from Etherscan: request to https://api-mumbai.etherscan.io/api?module=contract&action=getabi&address=0x3d3C0F4F5903C68f4635066c0DCc902F0CD54D4a failed, reason: getaddrinfo ENOTFOUND api-mumbai.etherscan.io

This makes sense as the contract was deployed on the polygon mumbai network.

**Comment by banjtheman** [comment]
Hey thanks for the feedback.
The ABI should be in the `./build/contracts/` folder that you used in step 10. Enter that path manually when it prompts for the ABI_PATH
Ill update the steps to explicitly say use that for the ABI_PATH

**Comment by banjtheman** [comment]
Step 13 updated with more info
![image](https://user-images.githubusercontent.com/696254/141725835-92291bf0-fdff-4541-b655-0518c6c432c6.png)
